contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #plasmidcompare channel"
    url: https://nfcore.slack.com/channels/plasmidcompare
    about: Discussion about the nf-core/plasmidcompare pipeline
